final version
AlinaSadovskaya/BattleShip_LAB3 pull request #1
Opened 2020-12-09 16:29 UTC by AlinaSadovskaya

2020-12-14 14:03 UTC, gmltA reviewed
Ok, here's the deal: I can close this PR right now, but then you won't earn a recommendation to let you pass without the exam.

Or I can ask you to refactor some things in this project and then you'll have a chance to earn one.

What would you say to that?

2020-12-14 14:08 UTC, AlinaSadovskaya commented
let me try to fix some things)

2020-12-14 15:43 UTC, gmltA requested changes
Let's start with these and then we'll see.

2020-12-14 15:43 UTC, gmltA commented on app/src/main/java/com/lab3/lab3_game/Activities/GameActivity.java
> +    private ValueEventListener scoreView_2_listener;
Okay the main problem here is that you blend your UI and logic layers. You work with firebase directly from the activity, while the better architecture can look like this.

**Activity <-> ViewModel (<-> GameController) <-> NetworkService <-> Firebase**

Let's break each component down:
- **Activity** (or fragment) — your UI layer. It only works with views it contains, listens to updates in ViewModel and dispatches actions back to the ViewModel
- **ViewModel** — all the data (and related business logic) related to the current view. In your case, it is a view model for the game itself (or you can split it as 2 view models - for ship placement and for the game itself).
- **GameController** — optionally you can extract most of your game logic to separate service which is not connected to UI and ViewModel in any way. But you can also handle game state directly in ViewModel. Here you should have all the actions user can perform in game.
- **NetworkService** — a wrapper around your actual network implementation. It works like a repository in some way: it takes data from your app and sends it somewhere as well as takes data from the remote source and returns it back. Why do we need this class? To introduce and adaptor that hides actual connectivity implementation.

2020-12-14 15:43 UTC, gmltA commented on app/src/main/java/com/lab3/lab3_game/Activities/GameActivity.java
> +    private final int winPoints = 20;
Inside ViewModel you should store **GameState** object with all these values (along with opponent's references, turns and so on. **GameController** alters this state when user performs an action and then sends updates via **NetworkService** to Firebase.

2020-12-18 13:12 UTC, gmltA reviewed
Much better. Are you going to refactor this further or that's it?)

2020-12-18 13:21 UTC, AlinaSadovskaya commented
I thought this was the final version) but if necessary, I can add viewmodels to the rest of the activity

2020-12-18 14:45 UTC, gmltA commented
How about game state extraction and further logic separation?

2020-12-18 15:10 UTC, AlinaSadovskaya commented
okey) I'll try to do it

2020-12-27 17:34 UTC, gmltA approved these changes
Okay that's enough. Good luck.

2021-03-23 13:23 UTC, merged